### PR TITLE
Add a github action to run the ginkgo tests on each PR

### PR DESCRIPTION
**Pull request by garethjevans**
Depends on #50

### CODE REVIEW

**Comment by KevinJCross** [comment]
@garethjevans would you mind merging this in so I can open A pr with my changes ?

**Comment by KevinJCross** [comment]
@ctlong would you mind merging this for @garethjevans ?
Ive got another PR for ginkgo v2 (and slight improvements) I'd like to create but I based it off @garethjevans fork.

**Comment by ctlong** [comment]
@KevinJCross I would not advise basing your PR off of this branch. The go mod changes here were superseded by https://github.com/cloudfoundry/cf-test-helpers/pull/54, which I imagine is what you care about.

**Comment by ctlong** [comment]
Closing for lack of activity

**Pull request closed without merging**
